---
- hosts: tag_ansible_group_bounce_server
  remote_user: ubuntu
  become: true
  gather_facts: false

  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
      tags: always 
    # action: setup will gather facts after python2 has been installed
    - action: setup

  tasks:
    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        reload: True
    - name: Create Iptables NAT chain
      iptables:
        table: nat
        chain: POSTROUTING
        jump: MASQUERADE
        comment: Ansible NAT Masquerade
    - name: Create Iptables redirection chain
      iptables:
        table: nat
        chain: PREROUTING
        protocol: "{{ item.proto }}"
        destination_port: "{{ item.dport }}"
        jump: DNAT
        to_destination: "{{ item.to_destination_address }}:{{ item.to_destination_port }}"
        comment: "{{ item.comment }}"
      with_items: "{{ redirect_services }}"
    - name: Ensure SG is set up
      local_action: 
        module: ec2_group
        name: "{{ ec2_security_group }}"
        description: bounce EC2 group
        vpc_id: "{{ ec2_vpc_id }}"
        region: "{{ ec2_region }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        aws_access_key: "{{ ec2_access_key }}"
        rules:
          - proto: "{{ item.proto }}"
            from_port: "{{ item.dport }}"
            to_port: "{{ item.dport }}"
            cidr_ip: 0.0.0.0/0
      with_items: 
        - "{{ redirect_services }}"
        - proto: tcp
          dport: 22
      become: false
