---
#Terminate the instances we created and tagged earlier

- hosts: tag_ansible_group_bounce_server
  connection: local

  tasks:
  - name: Terminate instances
    local_action: ec2
      state='absent'
      instance_ids='{{ ec2_id }}'
      region='{{ ec2_region }}'
      aws_secret_key="{{ ec2_secret_key }}"
      aws_access_key="{{ ec2_access_key }}"
      wait=True

- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Remove SG
    ec2_group:
      name: "{{ ec2_security_group }}"
      description: bounce EC2 group
      vpc_id: "{{ ec2_vpc_id }}"
      region: "{{ ec2_region }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      aws_access_key: "{{ ec2_access_key }}"
      state: absent
